==31805== Memcheck, a memory error detector
==31805== Copyright (C) 2002-2013, and GNU GPL'd, by Julian Seward et al.
==31805== Using Valgrind-3.10.0.SVN and LibVEX; rerun with -h for copyright info
==31805== Command: ./TestInteger
==31805== 
Running main() from gtest_main.cc
[==========] Running 86 tests from 1 test case.
[----------] Global test environment set-up.
[----------] 86 tests from IntegerFixture
[ RUN      ] IntegerFixture.shift_left1
[       OK ] IntegerFixture.shift_left1 (28 ms)
[ RUN      ] IntegerFixture.shift_left2
[       OK ] IntegerFixture.shift_left2 (4 ms)
[ RUN      ] IntegerFixture.shift_left3
[       OK ] IntegerFixture.shift_left3 (4 ms)
[ RUN      ] IntegerFixture.shift_right1
TestInteger.c++:79: Failure
Value of: result
  Actual: { 0, 0 }
Expected: correctVector
Which is: { 1, 2 }
[  FAILED  ] IntegerFixture.shift_right1 (33 ms)
[ RUN      ] IntegerFixture.shift_right2
TestInteger.c++:88: Failure
Value of: result
  Actual: { 0 }
Expected: correctVector
Which is: { 1 }
[  FAILED  ] IntegerFixture.shift_right2 (6 ms)
[ RUN      ] IntegerFixture.shift_right3
[       OK ] IntegerFixture.shift_right3 (4 ms)
[ RUN      ] IntegerFixture.plus_digits1
==31805== Invalid write of size 4
==31805==    at 0x42F1D5: int* std::__copy_move<false, false, std::random_access_iterator_tag>::__copy_m<std::_Deque_iterator<int, int&, int*>, int*>(std::_Deque_iterator<int, int&, int*>, std::_Deque_iterator<int, int&, int*>, int*) (in /v/filer4b/v38q001/jeremiah/Documents/cs378-integer/TestInteger)
==31805==    by 0x42E45B: int* std::__copy_move_a<false, std::_Deque_iterator<int, int&, int*>, int*>(std::_Deque_iterator<int, int&, int*>, std::_Deque_iterator<int, int&, int*>, int*) (in /v/filer4b/v38q001/jeremiah/Documents/cs378-integer/TestInteger)
==31805==    by 0x42D3F1: __gnu_cxx::__normal_iterator<int*, std::vector<int, std::allocator<int> > > std::__copy_move_a2<false, std::_Deque_iterator<int, int&, int*>, __gnu_cxx::__normal_iterator<int*, std::vector<int, std::allocator<int> > > >(std::_Deque_iterator<int, int&, int*>, std::_Deque_iterator<int, int&, int*>, __gnu_cxx::__normal_iterator<int*, std::vector<int, std::allocator<int> > >) (in /v/filer4b/v38q001/jeremiah/Documents/cs378-integer/TestInteger)
==31805==    by 0x42BC43: __gnu_cxx::__normal_iterator<int*, std::vector<int, std::allocator<int> > > std::copy<std::_Deque_iterator<int, int&, int*>, __gnu_cxx::__normal_iterator<int*, std::vector<int, std::allocator<int> > > >(std::_Deque_iterator<int, int&, int*>, std::_Deque_iterator<int, int&, int*>, __gnu_cxx::__normal_iterator<int*, std::vector<int, std::allocator<int> > >) (in /v/filer4b/v38q001/jeremiah/Documents/cs378-integer/TestInteger)
==31805==    by 0x4297F9: __gnu_cxx::__normal_iterator<int*, std::vector<int, std::allocator<int> > > plus_digits<__gnu_cxx::__normal_iterator<int*, std::vector<int, std::allocator<int> > >, __gnu_cxx::__normal_iterator<int*, std::vector<int, std::allocator<int> > >, __gnu_cxx::__normal_iterator<int*, std::vector<int, std::allocator<int> > > >(__gnu_cxx::__normal_iterator<int*, std::vector<int, std::allocator<int> > >, __gnu_cxx::__normal_iterator<int*, std::vector<int, std::allocator<int> > >, __gnu_cxx::__normal_iterator<int*, std::vector<int, std::allocator<int> > >, __gnu_cxx::__normal_iterator<int*, std::vector<int, std::allocator<int> > >, __gnu_cxx::__normal_iterator<int*, std::vector<int, std::allocator<int> > >) (in /v/filer4b/v38q001/jeremiah/Documents/cs378-integer/TestInteger)
==31805==    by 0x4077B1: IntegerFixture_plus_digits1_Test::TestBody() (in /v/filer4b/v38q001/jeremiah/Documents/cs378-integer/TestInteger)
==31805==    by 0x45DB82: void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (in /v/filer4b/v38q001/jeremiah/Documents/cs378-integer/TestInteger)
==31805==    by 0x45059C: testing::Test::Run() (in /v/filer4b/v38q001/jeremiah/Documents/cs378-integer/TestInteger)
==31805==    by 0x450633: testing::TestInfo::Run() (in /v/filer4b/v38q001/jeremiah/Documents/cs378-integer/TestInteger)
==31805==    by 0x450734: testing::TestCase::Run() (in /v/filer4b/v38q001/jeremiah/Documents/cs378-integer/TestInteger)
==31805==    by 0x4509AC: testing::internal::UnitTestImpl::RunAllTests() (in /v/filer4b/v38q001/jeremiah/Documents/cs378-integer/TestInteger)
==31805==    by 0x450C8D: testing::UnitTest::Run() (in /v/filer4b/v38q001/jeremiah/Documents/cs378-integer/TestInteger)
==31805==  Address 0x0 is not stack'd, malloc'd or (recently) free'd
==31805== 
==31805== 
==31805== Process terminating with default action of signal 11 (SIGSEGV)
==31805==  Access not within mapped region at address 0x0
==31805==    at 0x42F1D5: int* std::__copy_move<false, false, std::random_access_iterator_tag>::__copy_m<std::_Deque_iterator<int, int&, int*>, int*>(std::_Deque_iterator<int, int&, int*>, std::_Deque_iterator<int, int&, int*>, int*) (in /v/filer4b/v38q001/jeremiah/Documents/cs378-integer/TestInteger)
==31805==    by 0x42E45B: int* std::__copy_move_a<false, std::_Deque_iterator<int, int&, int*>, int*>(std::_Deque_iterator<int, int&, int*>, std::_Deque_iterator<int, int&, int*>, int*) (in /v/filer4b/v38q001/jeremiah/Documents/cs378-integer/TestInteger)
==31805==    by 0x42D3F1: __gnu_cxx::__normal_iterator<int*, std::vector<int, std::allocator<int> > > std::__copy_move_a2<false, std::_Deque_iterator<int, int&, int*>, __gnu_cxx::__normal_iterator<int*, std::vector<int, std::allocator<int> > > >(std::_Deque_iterator<int, int&, int*>, std::_Deque_iterator<int, int&, int*>, __gnu_cxx::__normal_iterator<int*, std::vector<int, std::allocator<int> > >) (in /v/filer4b/v38q001/jeremiah/Documents/cs378-integer/TestInteger)
==31805==    by 0x42BC43: __gnu_cxx::__normal_iterator<int*, std::vector<int, std::allocator<int> > > std::copy<std::_Deque_iterator<int, int&, int*>, __gnu_cxx::__normal_iterator<int*, std::vector<int, std::allocator<int> > > >(std::_Deque_iterator<int, int&, int*>, std::_Deque_iterator<int, int&, int*>, __gnu_cxx::__normal_iterator<int*, std::vector<int, std::allocator<int> > >) (in /v/filer4b/v38q001/jeremiah/Documents/cs378-integer/TestInteger)
==31805==    by 0x4297F9: __gnu_cxx::__normal_iterator<int*, std::vector<int, std::allocator<int> > > plus_digits<__gnu_cxx::__normal_iterator<int*, std::vector<int, std::allocator<int> > >, __gnu_cxx::__normal_iterator<int*, std::vector<int, std::allocator<int> > >, __gnu_cxx::__normal_iterator<int*, std::vector<int, std::allocator<int> > > >(__gnu_cxx::__normal_iterator<int*, std::vector<int, std::allocator<int> > >, __gnu_cxx::__normal_iterator<int*, std::vector<int, std::allocator<int> > >, __gnu_cxx::__normal_iterator<int*, std::vector<int, std::allocator<int> > >, __gnu_cxx::__normal_iterator<int*, std::vector<int, std::allocator<int> > >, __gnu_cxx::__normal_iterator<int*, std::vector<int, std::allocator<int> > >) (in /v/filer4b/v38q001/jeremiah/Documents/cs378-integer/TestInteger)
==31805==    by 0x4077B1: IntegerFixture_plus_digits1_Test::TestBody() (in /v/filer4b/v38q001/jeremiah/Documents/cs378-integer/TestInteger)
==31805==    by 0x45DB82: void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (in /v/filer4b/v38q001/jeremiah/Documents/cs378-integer/TestInteger)
==31805==    by 0x45059C: testing::Test::Run() (in /v/filer4b/v38q001/jeremiah/Documents/cs378-integer/TestInteger)
==31805==    by 0x450633: testing::TestInfo::Run() (in /v/filer4b/v38q001/jeremiah/Documents/cs378-integer/TestInteger)
==31805==    by 0x450734: testing::TestCase::Run() (in /v/filer4b/v38q001/jeremiah/Documents/cs378-integer/TestInteger)
==31805==    by 0x4509AC: testing::internal::UnitTestImpl::RunAllTests() (in /v/filer4b/v38q001/jeremiah/Documents/cs378-integer/TestInteger)
==31805==    by 0x450C8D: testing::UnitTest::Run() (in /v/filer4b/v38q001/jeremiah/Documents/cs378-integer/TestInteger)
==31805==  If you believe this happened as a result of a stack
==31805==  overflow in your program's main thread (unlikely but
==31805==  possible), you can try to increase the size of the
==31805==  main thread stack using the --main-stacksize= flag.
==31805==  The main thread stack size used in this run was 16777216.
==31805== 
==31805== HEAP SUMMARY:
==31805==     in use at exit: 26,834 bytes in 380 blocks
==31805==   total heap usage: 1,094 allocs, 714 frees, 103,993 bytes allocated
==31805== 
==31805== LEAK SUMMARY:
==31805==    definitely lost: 0 bytes in 0 blocks
==31805==    indirectly lost: 0 bytes in 0 blocks
==31805==      possibly lost: 7,238 bytes in 185 blocks
==31805==    still reachable: 19,596 bytes in 195 blocks
==31805==         suppressed: 0 bytes in 0 blocks
==31805== Rerun with --leak-check=full to see details of leaked memory
==31805== 
==31805== For counts of detected and suppressed errors, rerun with: -v
==31805== ERROR SUMMARY: 1 errors from 1 contexts (suppressed: 0 from 0)
Segmentation fault (core dumped)
